name: PR API Trigger

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  send-api-request:
    runs-on: ubuntu-latest

    steps:
      - name: Send API Request to Server
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"event\": ${{ toJson(github.event) }}, \"action\": \"${{ github.event.action }}\", \"pr_number\": \"${{ github.event.pull_request.number }}\"}" \
          http://13.234.112.119:3000/api/pr
