name: PR API Trigger

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  send-api-request:
    runs-on: ubuntu-latest

    steps:
      - name: Send API Request to Server
        run: |
          curl "13.235.132.227:3000/api/pr?event=pull_request&action=${{ github.event.action }}&pr_number=${{ github.event.pull_request.number }}"
